<a href="https://colab.research.google.com/github/giisg/desktop-tutorial/blob/HW/finalProjectV1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import io
import numpy as np
from sklearn import preprocessing 
from sklearn import svm
from sklearn import metrics
import math

In [ ]:
df = pd.read_csv("drive/My Drive/train.csv")

In [ ]:
df.head()

ID  age         job   marital  ... pdays previous  poutcome subscribed
0  26110   56      admin.   married  ...    -1        0   unknown         no
1  40576   31     unknown   married  ...    -1        0   unknown         no
2  15320   27    services   married  ...    -1        0   unknown         no
3  43962   57  management  divorced  ...    84        3   success        yes
4  29842   31  technician   married  ...    -1        0   unknown         no

[5 rows x 18 columns]

In [ ]:
df.shape

(31647, 18)

In [ ]:
df.isnull().sum()

ID            0
age           0
job           0
marital       0
education     0
default       0
balance       0
housing       0
loan          0
contact       0
day           0
month         0
duration      0
campaign      0
pdays         0
previous      0
poutcome      0
subscribed    0
dtype: int64

In [ ]:
df['month'].unique()

array(['nov', 'jul', 'jun', 'feb', 'sep', 'jan', 'may', 'aug', 'apr',
       'oct', 'mar', 'dec'], dtype=object)

In [ ]:
df['poutcome'].unique()

array(['unknown', 'success', 'failure', 'other'], dtype=object)

In [ ]:
df['contact'].unique()

array(['telephone', 'cellular', 'unknown'], dtype=object)

In [ ]:
df['loan'].unique()

array(['no', 'yes'], dtype=object)

In [ ]:
df['housing'].unique()

array(['no', 'yes'], dtype=object)

In [ ]:
df['education'].unique()

array(['unknown', 'secondary', 'tertiary', 'primary'], dtype=object)

In [ ]:
df['marital'].unique()

array(['married', 'divorced', 'single'], dtype=object)

In [ ]:
df['job'].unique()

array(['admin.', 'unknown', 'services', 'management', 'technician',
       'retired', 'blue-collar', 'housemaid', 'self-employed', 'student',
       'entrepreneur', 'unemployed'], dtype=object)

In [ ]:
df['subscribed'].unique()

array(['no', 'yes'], dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
df['poutcome'] = le.fit_transform(df['poutcome'])
df['contact'] = le.fit_transform(df['contact'])
df['loan'] = le.fit_transform(df['loan'])
df['housing'] = le.fit_transform(df['housing'])
df['education'] = le.fit_transform(df['education'])
df['marital'] = le.fit_transform(df['marital'])
df['job'] = le.fit_transform(df['job'])
df['default'] = le.fit_transform(df['default'])
df['subscribed'] = le.fit_transform(df['subscribed'])

In [ ]:
df.head()

ID  age  job  marital  ...  pdays  previous  poutcome  subscribed
0  26110   56    0        1  ...     -1         0         3           0
1  40576   31   11        1  ...     -1         0         3           0
2  15320   27    7        1  ...     -1         0         3           0
3  43962   57    4        0  ...     84         3         2           1
4  29842   31    9        1  ...     -1         0         3           0

[5 rows x 18 columns]

In [ ]:
df['month'].unique()

array(['nov', 'jul', 'jun', 'feb', 'sep', 'jan', 'may', 'aug', 'apr',
       'oct', 'mar', 'dec'], dtype=object)

In [ ]:
df['month'] = [1 if d == 'jan' else 2 if d == 'feb' else 3 if d =='mar' else 4
        if d == 'apr' else 5 if d == 'may' else 6 if d =='jun' else 7 
        if d == 'jul' else 8 if d == 'aug' else 9 if d =='sep' else 10
        if d == 'oct' else 11 if d == 'nov' else 12 for d in df['month']]

In [ ]:
df.head()

ID  age  job  marital  ...  pdays  previous  poutcome  subscribed
0  26110   56    0        1  ...     -1         0         3           0
1  40576   31   11        1  ...     -1         0         3           0
2  15320   27    7        1  ...     -1         0         3           0
3  43962   57    4        0  ...     84         3         2           1
4  29842   31    9        1  ...     -1         0         3           0

[5 rows x 18 columns]

In [ ]:
Y = df['subscribed'].values
X = df.drop('subscribed', 1)

In [ ]:
X.head()

ID  age  job  marital  ...  campaign  pdays  previous  poutcome
0  26110   56    0        1  ...         2     -1         0         3
1  40576   31   11        1  ...         2     -1         0         3
2  15320   27    7        1  ...         1     -1         0         3
3  43962   57    4        0  ...         1     84         3         2
4  29842   31    9        1  ...         1     -1         0         3

[5 rows x 17 columns]

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from tensorflow.keras import Sequential 
from tensorflow.keras.layers import Dense
from sklearn.naive_bayes import MultinomialNB
from sklearn import model_selection

In [ ]:
scaler = StandardScaler()
scaler.fit(X)
X = scaler.fit_transform(X)

In [ ]:
X

array([[-0.44662177, -2.14795986,  0.83301856, ...,  1.85633163,
         1.62834344, -0.62379744],
       [ 0.45258947, -1.85938479, -0.90169903, ..., -0.56781573,
        -0.6353757 ,  0.46243587],
       [-0.45508544,  0.05634011, -0.91829269, ...,  0.15689776,
        -1.13806085,  0.65364929],
       ...,
       [-0.09808296, -1.17465608, -1.67255876, ...,  1.21570758,
         0.45760487, -0.21655577],
       [ 4.7044462 ,  1.80612617,  1.62952171, ...,  0.4717399 ,
         0.16970364,  1.46581593],
       [-0.58279952, -0.03394224,  1.82966722, ...,  1.06693735,
        -1.20497435,  0.25001293]])

In [ ]:
pca = PCA(n_components=14)
pca.fit(X)
X = pca.fit_transform(X)

In [ ]:
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=1000)

In [ ]:
models = []
models.append(('log', LogisticRegression()))
models.append(('lr', LinearRegression()))
models.append(('KNN', KNeighborsClassifier()))
models.append(('SVM', SVC(C=0.1)))
models.append(('Gaussian', GaussianNB()))
models.append(('nn', Sequential()))

In [ ]:
results = []
names = []
msg = []
for name, model in models:
    kfold = model_selection.KFold(n_splits=10, random_state=42)
    if name == 'lr':
      model.fit(X_train, Y_train)
      lr_score = model_selection.cross_val_score(model,X_train, Y_train,cv=kfold).mean()
      cv_results = lr_score
    elif name == 'nn':
      model.add(Dense(50, activation='tanh',input_shape=(14,)))
      model.add(Dense(30, activation='sigmoid'))
      model.add(Dense(1, activation='sigmoid'))
      model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
      model.fit(X_train,Y_train, epochs=30, batch_size=10)
      test_los, test_acc = model.evaluate(X_test, Y_test)
      msg.append("{}: {}".format(name, test_acc))
    else:
      cv_results = model_selection.cross_val_score(model, X_train, Y_train, cv=kfold, scoring='accuracy')
    results.append(cv_results)
    names.append(name)
    msg.append("{}: {}".format(name, cv_results.mean()))
    print(msg)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


['log: 0.8922465066664669']
['log: 0.8922465066664669', 'lr: 0.22692269096018802']


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


['log: 0.8922465066664669', 'lr: 0.22692269096018802', 'KNN: 0.890982340307205']


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


['log: 0.8922465066664669', 'lr: 0.22692269096018802', 'KNN: 0.890982340307205', 'SVM: 0.8917331877764691']
['log: 0.8922465066664669', 'lr: 0.22692269096018802', 'KNN: 0.890982340307205', 'SVM: 0.8917331877764691', 'Gaussian: 0.8815421787216089']


/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning
/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


Epoch 1/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2500 - accuracy: 0.8922
Epoch 2/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2283 - accuracy: 0.8986
Epoch 3/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2207 - accuracy: 0.9007
Epoch 4/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2155 - accuracy: 0.9025
Epoch 5/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2126 - accuracy: 0.9030
Epoch 6/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2101 - accuracy: 0.9050
Epoch 7/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2081 - accuracy: 0.9046
Epoch 8/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2063 - accuracy: 0.9060
Epoch 9/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.2053 - accuracy: 0.9070
Epoch 10/30
2532/2532 [==============================] - 3s 1ms/step - loss: 0.203

In [ ]:
lr_score

0.22692269096018802

In [ ]:
res = msg[0:6]

In [ ]:
res

['log: 0.8922465066664669',
 'lr: 0.22692269096018802',
 'KNN: 0.890982340307205',
 'SVM: 0.8917331877764691',
 'Gaussian: 0.8815421787216089',
 'nn: 0.9061611294746399']

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 50)                750       
_________________________________________________________________
dense_1 (Dense)              (None, 30)                1530      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 31        
Total params: 2,311
Trainable params: 2,311
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_curve, auc

In [ ]:
kfold = model_selection.KFold(n_splits=10, random_state=42)

/usr/local/lib/python3.6/dist-packages/sklearn/model_selection/_split.py:296: FutureWarning: Setting a random_state has no effect since shuffle is False. This will raise an error in 0.24. You should leave random_state to its default (None), or set shuffle=True.
  FutureWarning


In [ ]:
log = LogisticRegression()
log.fit(X_train, Y_train)
lr = LinearRegression()
lr.fit(X_train, Y_train)
SVM = SVC(C=0.1)
SVM.fit(X_train, Y_train)
KNN = KNeighborsClassifier()
KNN.fit(X_train, Y_train)
Gaussian = GaussianNB()
Gaussian.fit(X_train, Y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [ ]:
print(model_selection.cross_val_score(log,X_train, Y_train,cv=kfold).mean())
print(model_selection.cross_val_score(lr,X_train, Y_train,cv=kfold).mean())
print(model_selection.cross_val_score(SVM,X_train, Y_train,cv=kfold).mean())
print(model_selection.cross_val_score(KNN,X_train, Y_train,cv=kfold).mean())
print(model_selection.cross_val_score(Gaussian,X_train, Y_train,cv=kfold).mean())

0.8922465066664669
0.22692269096018802
0.8917331877764691
0.890982340307205
0.8815421787216089


In [ ]:
log_predictions = log.predict(X_test)
lr_predictions = lr.predict(X_test)
SVM_predictions = SVM.predict(X_test)
KNN_predictions = KNN.predict(X_test)
Gaussian_predictions = Gaussian.predict(X_test)

In [ ]:
lr_predictions

array([0.03075036, 0.16241313, 0.12428347, ..., 0.41430147, 0.40978995,
       0.05430992])

In [ ]:
print("Accuracy : ", accuracy_score(Y_test, log_predictions))
print("Confusion Matrix : \n",confusion_matrix(Y_test, log_predictions))
print("Classification Report: \n",classification_report(Y_test, log_predictions))

Accuracy :  0.8903633491311217
Confusion Matrix : 
 [[5453  122]
 [ 572  183]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.98      0.94      5575
           1       0.60      0.24      0.35       755

    accuracy                           0.89      6330
   macro avg       0.75      0.61      0.64      6330
weighted avg       0.87      0.89      0.87      6330



In [ ]:
print("Accuracy : ", accuracy_score(Y_test, SVM_predictions))
print("Confusion Matrix : \n",confusion_matrix(Y_test, SVM_predictions))
print("Classification Report: \n",classification_report(Y_test, SVM_predictions))

Accuracy :  0.8897314375987362
Confusion Matrix : 
 [[5529   46]
 [ 652  103]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.89      0.99      0.94      5575
           1       0.69      0.14      0.23       755

    accuracy                           0.89      6330
   macro avg       0.79      0.56      0.58      6330
weighted avg       0.87      0.89      0.86      6330



In [ ]:
print("Accuracy : ", accuracy_score(Y_test, KNN_predictions))
print("Confusion Matrix : \n",confusion_matrix(Y_test, KNN_predictions))
print("Classification Report: \n",classification_report(Y_test, KNN_predictions))

Accuracy :  0.8890995260663507
Confusion Matrix : 
 [[5385  190]
 [ 512  243]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.97      0.94      5575
           1       0.56      0.32      0.41       755

    accuracy                           0.89      6330
   macro avg       0.74      0.64      0.67      6330
weighted avg       0.87      0.89      0.88      6330



In [ ]:
print("Accuracy : ", accuracy_score(Y_test, Gaussian_predictions))
print("Confusion Matrix : \n",confusion_matrix(Y_test, Gaussian_predictions))
print("Classification Report: \n",classification_report(Y_test, Gaussian_predictions))

Accuracy :  0.879304897314376
Confusion Matrix : 
 [[5351  224]
 [ 540  215]]
Classification Report: 
               precision    recall  f1-score   support

           0       0.91      0.96      0.93      5575
           1       0.49      0.28      0.36       755

    accuracy                           0.88      6330
   macro avg       0.70      0.62      0.65      6330
weighted avg       0.86      0.88      0.86      6330



In [ ]:
fpr_gnb, tpr_gnb,thresholds_gnb = roc_curve(Y_test, log_predictions)

In [ ]:
auc(fpr_gnb,tpr_gnb)

0.6102503489442579

In [ ]:
fpr_gnb, tpr_gnb,thresholds_gnb = roc_curve(Y_test, SVM_predictions)

In [ ]:
auc(fpr_gnb,tpr_gnb)

0.5640863599916848

In [ ]:
fpr_gnb, tpr_gnb,thresholds_gnb = roc_curve(Y_test, KNN_predictions)
auc(fpr_gnb,tpr_gnb)

0.6438867935734862

In [ ]:
fpr_gnb, tpr_gnb,thresholds_gnb = roc_curve(Y_test, Gaussian_predictions)
auc(fpr_gnb,tpr_gnb)

0.6222944198616102