In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as pl

In [2]:
data = pd.read_csv('drive/My Drive/bank-full.csv')
data.head()

age           job  marital  education  ... pdays  previous poutcome   y
0   58    management  married   tertiary  ...    -1         0  unknown  no
1   44    technician   single  secondary  ...    -1         0  unknown  no
2   33  entrepreneur  married  secondary  ...    -1         0  unknown  no
3   47   blue-collar  married    unknown  ...    -1         0  unknown  no
4   33       unknown   single    unknown  ...    -1         0  unknown  no

[5 rows x 17 columns]

In [3]:
data.shape

(45211, 17)

In [4]:
data.isnull().sum()

age          0
job          0
marital      0
education    0
default      0
balance      0
housing      0
loan         0
contact      0
day          0
month        0
duration     0
campaign     0
pdays        0
previous     0
poutcome     0
y            0
dtype: int64

In [5]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [6]:

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [7]:
data['education'].unique()

array(['tertiary', 'secondary', 'unknown', 'primary'], dtype=object)

In [8]:
data['contact'].unique()

array(['unknown', 'cellular', 'telephone'], dtype=object)

In [9]:
data['job'].unique()

array(['management', 'technician', 'entrepreneur', 'blue-collar',
       'unknown', 'retired', 'admin.', 'services', 'self-employed',
       'unemployed', 'housemaid', 'student'], dtype=object)

In [10]:
data['marital'].unique()

array(['married', 'single', 'divorced'], dtype=object)

In [11]:
data['job'] = le.fit_transform(data['job'])
data['marital'] = le.fit_transform(data['marital'])
data['education'] = le.fit_transform(data['education'])
data['default'] = le.fit_transform(data['default'])
data['housing'] = le.fit_transform(data['housing'])
data['loan'] = le.fit_transform(data['loan'])
data['contact'] = le.fit_transform(data['contact'])
data['month'] = le.fit_transform(data['month'])
data['poutcome'] = le.fit_transform(data['poutcome'])
data['y'] = le.fit_transform(data['y'])
data

age  job  marital  education  ...  pdays  previous  poutcome  y
0       58    4        1          2  ...     -1         0         3  0
1       44    9        2          1  ...     -1         0         3  0
2       33    2        1          1  ...     -1         0         3  0
3       47    1        1          3  ...     -1         0         3  0
4       33   11        2          3  ...     -1         0         3  0
...    ...  ...      ...        ...  ...    ...       ...       ... ..
45206   51    9        1          2  ...     -1         0         3  1
45207   71    5        0          0  ...     -1         0         3  1
45208   72    5        1          1  ...    184         3         2  1
45209   57    1        1          1  ...     -1         0         3  0
45210   37    2        1          1  ...    188        11         1  0

[45211 rows x 17 columns]

In [12]:
Y = data['y'].values

In [13]:
Y

array([0, 0, 0, ..., 1, 0, 0])

In [14]:
X = data.drop('y', 1)

In [15]:
X

age  job  marital  education  ...  campaign  pdays  previous  poutcome
0       58    4        1          2  ...         1     -1         0         3
1       44    9        2          1  ...         1     -1         0         3
2       33    2        1          1  ...         1     -1         0         3
3       47    1        1          3  ...         1     -1         0         3
4       33   11        2          3  ...         1     -1         0         3
...    ...  ...      ...        ...  ...       ...    ...       ...       ...
45206   51    9        1          2  ...         3     -1         0         3
45207   71    5        0          0  ...         2     -1         0         3
45208   72    5        1          1  ...         5    184         3         2
45209   57    1        1          1  ...         4     -1         0         3
45210   37    2        1          1  ...         2    188        11         1

[45211 rows x 16 columns]

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
X_std = StandardScaler().fit_transform(X)
X_std

array([[ 1.60696496, -0.10381968, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       [ 0.28852927,  1.42400783,  1.3683719 , ..., -0.41145311,
        -0.25194037,  0.44489814],
       [-0.74738448, -0.71495069, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       ...,
       [ 2.92540065,  0.20174582, -0.27576178, ...,  1.43618859,
         1.05047333, -0.56617504],
       [ 1.51279098, -1.02051619, -0.27576178, ..., -0.41145311,
        -0.25194037,  0.44489814],
       [-0.37068857, -0.71495069, -0.27576178, ...,  1.4761376 ,
         4.52357654, -1.57724822]])

In [18]:
import numpy.linalg as linalg

In [19]:
cov_mat = np.cov(X_std.T)

In [20]:
eig_vals,eig_vecs = linalg.eig(cov_mat)

In [21]:
eig_vals

array([2.38158304, 0.1391822 , 1.68623819, 1.49067024, 1.21976059,
       0.5183141 , 0.54834835, 0.62218493, 1.12667059, 0.76930274,
       1.01463856, 0.97624967, 0.91432708, 0.93100798, 0.82224897,
       0.83962667])

In [22]:
eig_vecs

array([[-4.07224865e-02,  1.32064851e-02, -7.78855106e-02,
         6.71250182e-01,  1.06074923e-01,  5.77346915e-01,
         3.52752267e-01,  1.48722080e-01, -4.80978511e-02,
        -1.46343696e-01,  1.47825552e-01,  1.15422170e-02,
         6.21159843e-02, -2.79913693e-02, -5.55634015e-03,
         1.50216816e-03],
       [ 5.44707284e-04,  5.91568331e-03, -3.07656309e-01,
        -1.54001776e-01,  1.48076663e-01,  8.05841187e-03,
        -1.55052610e-02, -5.39868791e-04, -3.68249226e-02,
         2.99128743e-01,  5.14299772e-01,  7.43060139e-02,
         2.43818497e-01, -4.13187015e-01, -5.13555160e-01,
         6.77777720e-02],
       [ 4.40406899e-02,  1.47885971e-03, -7.02634073e-02,
        -6.25956757e-01,  5.28324264e-02,  4.63771627e-01,
         3.34572829e-01,  1.52235368e-01,  9.43967120e-03,
        -2.64710008e-01, -1.74881089e-01,  3.68150361e-02,
        -9.91212248e-02,  2.10410155e-01, -3.02365072e-01,
        -2.62321329e-02],
       [ 3.76838680e-02,  1.17052993e

In [23]:
from sklearn.decomposition import PCA

In [24]:
pca = PCA(n_components=13)

In [25]:
X_feature = pca.fit_transform(X_std)

In [26]:
X_feature

array([[-0.78890923, -1.31830434,  0.77622944, ..., -0.90311143,
         0.2568709 , -0.01887746],
       [-0.73076082, -1.2819238 , -1.05772434, ...,  1.19940318,
        -0.04916124, -0.09366281],
       [-0.82883489, -2.38356872, -0.29819299, ..., -0.06000458,
         0.29917438,  0.2669997 ],
       ...,
       [ 1.57891358,  0.5852589 ,  2.50001712, ...,  0.88610432,
         1.20431529, -0.98892856],
       [-0.94353462, -0.40619616,  1.43027295, ..., -0.12062925,
         1.568343  , -0.77033524],
       [ 3.93389431, -0.3128333 ,  0.60783749, ...,  0.63598229,
         2.11562872,  2.14059428]])

In [27]:
pca.explained_variance_ratio_

array([0.14884565, 0.10538756, 0.09316483, 0.07623335, 0.07041535,
       0.06341351, 0.06101426, 0.05818671, 0.05714418, 0.05247551,
       0.05138942, 0.04808036, 0.0388857 ])

In [28]:
X_feature.shape

(45211, 13)

In [29]:
Y.shape

(45211,)

方法一

In [30]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,Y_train,Y_test = train_test_split(X_feature,Y,test_size=0.2)
lr = LinearRegression(normalize=True)

In [32]:
lr.fit(X_train,Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [33]:
lr.intercept_

0.11756857219897995

In [34]:
lr.coef_

array([ 0.02862473,  0.03244124,  0.00031982,  0.0567035 , -0.04159969,
       -0.0083023 ,  0.09755631,  0.00644668, -0.03237002,  0.0167248 ,
        0.00506878,  0.03958919, -0.00634121])

In [35]:
lr.score(X_test,Y_test)

0.19880762883800052

In [36]:
from sklearn.model_selection import cross_val_score

In [37]:
scores = cross_val_score(lr,X_test,Y_test,cv=10,scoring='r2')

In [38]:
scores

array([0.20030251, 0.06804181, 0.15802471, 0.20573398, 0.17433444,
       0.21672803, 0.21609011, 0.22597732, 0.21618341, 0.24314982])

In [39]:
scores.mean()

0.19245661446066314

方法二

In [40]:
from sklearn.linear_model import Ridge

In [41]:
rg = Ridge(alpha=0.007,normalize=True)

In [42]:
rg_score = cross_val_score(rg,X_test,Y_test,cv=10,scoring='r2')

In [43]:
rg_score

array([0.20041096, 0.07008078, 0.15831496, 0.2057086 , 0.17477347,
       0.216851  , 0.21586026, 0.22563941, 0.21626037, 0.2429118 ])

In [44]:
rg_score.mean()

0.19268116092577559

In [45]:
from sklearn.linear_model import RidgeCV

In [46]:
rgcv = RidgeCV(alphas=(1.0,0.1,0.01,0.05,0.025,0.001,0.005,0.00025),normalize=True)

In [47]:
rgcv.fit(X_train,Y_train)

RidgeCV(alphas=array([1.0e+00, 1.0e-01, 1.0e-02, 5.0e-02, 2.5e-02, 1.0e-03, 5.0e-03,
       2.5e-04]),
        cv=None, fit_intercept=True, gcv_mode=None, normalize=True,
        scoring=None, store_cv_values=False)

In [48]:
rgcv.score(X_test,Y_test)

0.19884035494304086

In [49]:
rgcv.alpha_

0.001

方法三

In [50]:
from sklearn.linear_model import LassoCV

In [51]:
lscv = LassoCV(alphas=(1.0,0.1,0.01,0.05,0.025,0.001,0.005,0.00025),normalize=True)

In [52]:
lscv.fit(X_train,Y_train)

LassoCV(alphas=(1.0, 0.1, 0.01, 0.05, 0.025, 0.001, 0.005, 0.00025),
        copy_X=True, cv=None, eps=0.001, fit_intercept=True, max_iter=1000,
        n_alphas=100, n_jobs=None, normalize=True, positive=False,
        precompute='auto', random_state=None, selection='cyclic', tol=0.0001,
        verbose=False)

In [53]:
lscv.score(X_test,Y_test)

0.08459994521445657

In [54]:
lscv.alpha_

0.00025

方法四

In [55]:
from sklearn.linear_model import ElasticNet,ElasticNetCV

In [56]:
en = ElasticNet(alpha=0.001,l1_ratio=0.8,normalize=True)

In [57]:
en_score = cross_val_score(en,X_test,Y_test,cv=10,scoring='r2')

In [58]:
encv = ElasticNetCV(alphas=(1.0,0.1,0.01,0.05,0.025,0.001,0.005,0.00025),l1_ratio=(0.1,0.25,0.5,0.75,0.8),normalize=True)

In [59]:
encv.fit(X_train,Y_train)

ElasticNetCV(alphas=(1.0, 0.1, 0.01, 0.05, 0.025, 0.001, 0.005, 0.00025),
             copy_X=True, cv=None, eps=0.001, fit_intercept=True,
             l1_ratio=(0.1, 0.25, 0.5, 0.75, 0.8), max_iter=1000, n_alphas=100,
             n_jobs=None, normalize=True, positive=False, precompute='auto',
             random_state=None, selection='cyclic', tol=0.0001, verbose=0)

In [60]:
encv.score(X_test,Y_test)

0.049195639028242644

方法五

In [65]:
from sklearn.preprocessing import PolynomialFeatures

In [66]:
pf = PolynomialFeatures(degree=2)

In [73]:
xpf = pf.fit_transform(X_feature.reshape(-1,1))

In [74]:
xpf

array([[ 1.        , -0.78890923,  0.62237777],
       [ 1.        , -1.31830434,  1.73792632],
       [ 1.        ,  0.77622944,  0.60253214],
       ...,
       [ 1.        ,  0.63598229,  0.40447347],
       [ 1.        ,  2.11562872,  4.47588486],
       [ 1.        ,  2.14059428,  4.58214388]])

In [76]:
lr2 = LinearRegression(normalize=True)